version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.10"
  apt_packages:
    - graphviz
    - libboost-dev
    - pybind11-dev
    - libzmq3-dev
    - libjsoncpp-dev
    - clang-11
    - llvm-11-dev
    - libc++-11-dev
    - libc++abi-11-dev
    - libstdc++-11-dev
    - cmake
  jobs:
    pre_build:
      - python -m pip install virtualenvwrapper --break-system-packages
      - update-alternatives --remove-all clang++
      - update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang-11 100
      - ./build_multiverse.sh --only-src

python:
  install:
    - requirements: docs/requirements.txt

sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: false
