version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.10"
  apt_packages:
    - graphviz
    - libboost-dev
    - cmake
  jobs:
    pre_build:
      - python3 -m pip install virtualenvwrapper --break-system-packages
      - ./build_third_parties.sh --excludes mujoco usd blender
      - ./build_multiverse.sh --only-src

python:
  install:
    - requirements: docs/requirements.txt

sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: false
