version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.10"
  apt_packages:
    - graphviz
    - libboost-dev
    - cmake
  jobs:
    pre_build:
      - python -m pip install virtualenvwrapper --break-system-packages
      - git submodule update --init multiverse/external/pybind11
      - mkdir -p multiverse/build/pybind11
      - cd multiverse/build/pybind11 && cmake ../../external/pybind11 -DCMAKE_INSTALL_PREFIX=$pwd -Wno-deprecated -Wno-dev && cmake --build . && cmake --install .
      - ./build_multiverse.sh --only-src

python:
  install:
    - requirements: docs/requirements.txt

sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: false
