name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Run install.sh
      run: |
          chmod +x install.sh
          sudo ./install.sh

    - name: Run build.sh
      run: |
          chmod +x build.sh
          sudo ./build.sh

    - name: Run build_ws.sh
      run: |
          chmod +x build_ws.sh
          sudo ./build_ws.sh