name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: noetic-ros-core

    steps:
    - uses: actions/checkout@v3
    - name: build
      run: ./build.sh
