name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: betwo/github-setup-catkin@master
      with:
        ros-version: 'noetic'
        build-tool: 'catkin_tools'
        workspace: '$GITHUB_WORKSPACE'
    - run: cd universim_ws && catkin build
